name: Whisky Reviewer CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and test with Gradle
      run: ./gradlew clean build
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "target/surefire-reports/**/*.xml"
    - name: Gradle release
      if: github.ref == 'refs/heads/master'
      run: ./gradlew release -x test
    - name: Get version
      if: github.ref == 'refs/heads/master'
      run: echo "VERSION=$(./gradlew currentVersion -q -Prelease.quiet)" >> $GITHUB_ENV
    - name: GitHub release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.VERSION }}"
        prerelease: false
        files: |
          build/libs/*.jar
