name: Whisky Reviewer CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and test with Gradle
      run: ./gradlew clean build test
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "build/test-results/**/*.xml"
    - name: Gradle release
      if: github.ref == 'refs/heads/master'
      run: "./gradlew release -x test -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=${{ secrets.GITHUB_USER }} -Prelease.customPassword=${{ secrets.GITHUB_ACCESS_TOKEN }}"
